import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { AuthProvider } from "./AuthContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Navbar />
          <main className="relative grow">
            {children}
          </main>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
